/** Public surface of @zenith/shared — consumed by both the server and the web app. */
export * from './units.ts'
export * from './terms.ts'
export * from './ir/schema.ts'
export * from './template/parse.ts'
export * from './template/evaluate.ts'
export * from './template/variables.ts'
export * from './template/sequence.ts'
export * from './ir-to-svg/index.ts'
export * from './barcode/index.ts'
export * from './geometry/index.ts'
